version: '3.3'

volumes:
  mariadb_data_volume: {}

services:
  # Nginx
  app-nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:latest
    links:
      - app-php7
#    ports: # use nginx-proxy or provide your own port...
#      - 8800:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/srv/www:cached
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}

  # PHP
  app-php7:
    container_name: ${PROJECT_NAME}-php72
    build: ./docker/php
    links:
      - app-mariadb
#      - app-redis
    volumes:
      - .:/srv/www:cached
      - ~/.ssh:/root/.ssh # for composer
    environment:
      - XDEBUG_CONFIG=remote_host=$HOST_IP idekey=PHPSTORM

  # DB
  app-mariadb:
    container_name: ${PROJECT_NAME}-mariadb
    image: mariadb:10.3.0
    environment:
      MYSQL_ROOT_PASSWORD: Start@123
      MYSQL_USER: project
      MYSQL_PASSWORD: Password1
      MYSQL_DATABASE: project
    volumes:
      - mariadb_data_volume:/var/lib/mysql

  # Redis
#  app-redis:
#    container_name: ${PROJECT_NAME}-app-redis
#    image: redis:latest